title: Matthew Hanani
logo: /assets/img/pfp.jpg
description: I'm a fifth year Economics and Mathematics Student at McMaster University. My interests are statistics, probabalistic modelling, health economics, and public policy.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
