title: Matthew Hanani
logo: /assets/img/pfp.jpg
description: I'm a fifth year Economics and Mathematics Student at McMaster University. I'm interested in statistics, probabalistic modelling, health economics, and public policy.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
